### ISSUE TITLE
[Tracking] Issues

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/alter-housing#2]
# TODO
- [x] images
- [x] pages
- [x] styling
- [x] subtitle
- [x] description
- [x] slogan
- [x] social icons
- [x] `:nth-of-type(4n), :nth-of-type(4n-1)`
- [x] header align bottom
- [x] rooms form
- [x] favicon
- [x] mobile testing
- [ ] hero image on iPhone 4 (unreproducible)
- [x] cross-browser
  - [x] Safari
  - [x] Chrome
  - [x] Firefox
  - [x] IE
    - svg's don't work
    - excessive "search" button on index (100%)
- [x] outline
  - [x] what to do with "half-wrapper"?
- [x] padding svg's
- [x] quotes
- [x] padding footer

**Comment by Haroenv** [comment]
The hero image on iPhone 4 was an iOS 6 and 7 issue, fixed in iOS 8 and later.
